config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  root to: 'attendances#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/att.rb
class Att < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @attendances = Att.all
  end

  def new
    @attendance = Att.new
  end

  def create
    @attendance = Att.new(attendance_params)
    @attendance.save
    redirect_to attendances_path
  end

  def edit
    @attendance = find_att_by_id
  end

  def update
    @attendance = find_att_by_id
    @attendance.update(attendance_params)
    redirect_to attendances_path
  end

  private

  def attendance_params
    params.require(:att).permit(:id, :date, :work_from, :work_to, :break_from, :break_to, :description)
  end

  def find_att_by_id
    Att.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/edit.html.erb
<h2>修正</h2>
 
<%= form_for @attendance, url: attendance_path do |f| %>
  <div>
    <%= f.label :date, '日付' %>
    <%= f.text_field :date %>
  </div>
  <div>
    <%= f.label :work_from, '出勤時間' %>
    <%= f.text_field :work_from %>
  </div>
  <div>
    <%= f.label :work_to, '退勤時間' %>
    <%= f.text_field :work_to %>
  </div>
  <div>
    <%= f.label :break_from, '休憩開始時間' %>
    <%= f.text_field :break_from %>
  </div>
  <div>
    <%= f.label :break_to, '休憩終了時間' %>
    <%= f.text_field :break_to %>
  </div>
  <div>
    <%= f.label :description, '作業内容' %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit '送信' %>
  </div>
<% end %>

<%= link_to "戻る", attendances_path %>

app/views/attendances/index.html.erb
<div>
  <%= link_to '新規登録', new_attendance_path %>
<table>
  <tr>
      <th>日</th>
      <th>出勤</th>
      <th>退勤</th>
      <th>休憩始</th>
      <th>休憩終</th>
      <th>作業内容</th>
      <th>稼働</th>
  </tr>
  <% total_sum = 0 %>
  <% @attendances.each do |attendance| %>
    <tr>
      <td><%= attendance.date %></td>
      <td><%= attendance.work_from %></td>
      <td><%= attendance.work_to %></td>
      <td><%= attendance.break_from %></td>
      <td><%= attendance.break_to %></td>
      <td><%= attendance.description %></td>
      <td><% require 'time'; daily_sum = ((Time.parse(attendance.work_to) - Time.parse(attendance.work_from))/60/60) - ((Time.parse(attendance.break_to) - Time.parse(attendance.break_from))/60/60) %><%= daily_sum %></td>
      <td><%= link_to '修正', edit_attendance_path(attendance.id) %></td>
    </tr>
    <% total_sum += daily_sum %>
  <% end %>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><font color="red"><%= total_sum %></font></td>
        <td></td>
    </tr>
  </table>

app/views/attendances/new.html.erb
<h2>新規登録</h2>
 
<%= form_for @attendance, url: attendances_path do |f| %>
  <div>
    <%= f.label :date, '日付' %>
    <%= f.text_field :date %>
  </div>
  <div>
    <%= f.label :work_from, '出勤時間' %>
    <%= f.text_field :work_from %>
  </div>
  <div>
    <%= f.label :work_to, '退勤時間' %>
    <%= f.text_field :work_to %>
  </div>
  <div>
    <%= f.label :break_from, '休憩開始時間' %>
    <%= f.text_field :break_from %>
  </div>
  <div>
    <%= f.label :break_to, '休憩終了時間' %>
    <%= f.text_field :break_to %>
  </div>
  <div>
    <%= f.label :description, '作業内容' %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit '送信' %>
  </div>
<% end %>

<%= link_to "戻る", attendances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>